version: "3.8"

services:
  bot:
    container_name: ilt_bot
    build: .
    env_file:
      - .env
    volumes:
      - ./sqlite.db:/app/sqlite.db
      - ./service_account.json:/run/secrets/credentials.json:ro
    restart: always
